// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/hvossi92/gollama/src/templates/icons"

func Index(messages []templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = head().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<body><div class=\"game-container\"><div class=\"game-controls\"><div class=\"control-btn\" title=\"Help\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Question().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><a class=\"control-btn\" title=\"Save Game\" href=\"/save-games\" hx-target=\"body\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Save().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</a> <a class=\"control-btn\" title=\"Settings\" href=\"/settings\" hx-target=\"body\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Gear().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</a></div><div class=\"row g-2 mb-2\"><div class=\"col-12\"><!-- Scene Panel --><div class=\"panel scene-panel panel-corner-tl panel-corner-tr panel-corner-bl panel-corner-br\" style=\"background-image: url(&#39;/static/art/baldursgate.png&#39;); \" hx-get=\"/api/scene\" hx-trigger=\"load, sceneChange from:body\" hx-swap=\"outerHTML\"><div class=\"panel-header\">Current Location</div><div class=\"scene-overlay\">Ancient stone columns rise from the mist, their surfaces etched with mysterious runes that glow with a faint blue light.</div></div></div></div><div class=\"row g-2\"><!-- Character Panel - Always visible on mobile, smaller width --><div class=\"col-12 col-md-3 mb-2\" style=\"max-width: 300px;\"><div class=\"panel character-panel panel-corner-tl panel-corner-tr panel-corner-bl panel-corner-br\" hx-get=\"/api/character\" hx-trigger=\"load, characterUpdate from:body\" hx-swap=\"innerHTML\"><div class=\"panel-header\">Character - LazerPope\t</div><div class=\"character-image\" style=\"background-image: url(&#39;/static/art/tiefling.png&#39;); background-position-y: 0rem;\"></div></div></div><!-- Chat Panel - Full width on mobile --><div class=\"col-12 col-md mb-2\"><div class=\"panel chat-panel panel-corner-tl panel-corner-tr panel-corner-bl panel-corner-br\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(messages) > 0 {
			templ_7745c5c3_Err = ChatInterface(messages).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<button type=\"button\" hx-post=\"/start\" class=\"main-btn\" style=\"margin: 20%;\" hx-swap=\"outerHTML\" hx-disabled-elt=\"this\" hx-indicator=\"#indicator\">Start your adventure <span id=\"indicator\" class=\"htmx-indicator\">Travelling to the sword coast...</span></button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></div><!-- Enemy Panel - Full width on mobile --><div class=\"col-12 col-md-3 mb-2\" style=\"max-width: 300px;\"><div class=\"panel enemy-panel panel-corner-tl panel-corner-tr panel-corner-bl panel-corner-br\" hx-get=\"/api/enemy\" hx-trigger=\"load, enemyUpdate from:body\" hx-swap=\"innerHTML\"><div class=\"panel-header\">NPC - Scary skeleton</div><div class=\"enemy-image\" style=\"background-image: url(&#39;/static/art/skeleton.png&#39;); background-position-y: 0rem;\"></div></div></div></div></div><script>\n        // Auto-scroll chat to bottom\n        function scrollChatToBottom() {\n            const chatMessages = document.getElementById('chat-messages');\n            if (chatMessages) {\n                chatMessages.scrollTop = chatMessages.scrollHeight;\n            }\n        }\n\n        // Call on page load\n        document.addEventListener('DOMContentLoaded', scrollChatToBottom);\n\n        // Call when new messages are added\n        document.body.addEventListener('htmx:afterSwap', function (event) {\n            if (event.detail.target.id === 'chat-messages') {\n                scrollChatToBottom();\n            }\n        });\n    </script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
