// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func VectorUploadArea() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"card\" style=\"background-color: var(--chat-bg); border: 1px solid var(--message-border);\"><div class=\"card-body row\"><h5 class=\"card-title mb-4\" style=\"color: var(--body-color);\">Vector database upload area</h5><form hx-post=\"/vector\" enctype=\"multipart/form-data\" hx-target=\"#chat-messages\" class=\"mb-4\" hx-swap=\"beforeend\" hx-indicator=\"#upload-spinner\" hx-disabled-elt=\"#upload-disable\"><div class=\"mb-3\"><label for=\"image-upload\" class=\"form-label\" style=\"color: var(--body-color);\">Upload data to add to the vector database</label> <textarea class=\"form-control form-control-lg\" type=\"text\" name=\"vectors\" id=\"vector-upload\" placeholder=\"Paste your data here\"></textarea><div class=\"form-text\" style=\"color: var(--body-color);\"></div></div><button id=\"upload-disable\" type=\"submit\" class=\"btn btn-primary\"><i class=\"bi bi-cloud-upload me-2\"></i>Upload data</button> <span id=\"upload-spinner\" class=\"spinner-border spinner-border-sm htmx-indicator\" role=\"status\" aria-hidden=\"true\"></span> <button hx-get=\"/vector\" type=\"button\" class=\"btn btn-info\" hx-indicator=\"#read-vectors-spinner\" hx-disabled-elt=\"this\"><i class=\"bi bi-cloud-upload me-2\"></i>Read vectors</button> <span id=\"read-vectors-spinner\" class=\"spinner-border htmx-indicator spinner-border-sm\" role=\"status\" aria-hidden=\"true\"></span></form></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
