// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: settings.sql

package db

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT id, url, llm FROM settings
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(&i.ID, &i.Url, &i.Llm)
	return i, err
}

const insertSettings = `-- name: InsertSettings :exec
INSERT INTO settings (url, llm)
VALUES (?, ?)
`

type InsertSettingsParams struct {
	Url string
	Llm string
}

func (q *Queries) InsertSettings(ctx context.Context, arg InsertSettingsParams) error {
	_, err := q.db.ExecContext(ctx, insertSettings, arg.Url, arg.Llm)
	return err
}

const updateSettings = `-- name: UpdateSettings :exec
UPDATE settings SET url=?, llm=? WHERE id=1
`

type UpdateSettingsParams struct {
	Url string
	Llm string
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSettings, arg.Url, arg.Llm)
	return err
}
