CREATE TABLE IF NOT EXISTS save_games (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    created TEXT DEFAULT CURRENT_TIMESTAMP
) STRICT;

CREATE TABLE IF NOT EXISTS chat_messages (
		id INTEGER PRIMARY KEY,
		role TEXT NOT NULL,
		content TEXT NOT NULL,
		save_game_id INTEGER NOT NULL,
		created TEXT DEFAULT CURRENT_TIMESTAMP,
		FOREIGN KEY (save_game_id) REFERENCES save_games(id) ON DELETE CASCADE
	) STRICT;

CREATE TABLE IF NOT EXISTS settings (
    id INTEGER PRIMARY KEY,
    url TEXT NOT NULL,
    llm TEXT NOT NULL
) STRICT;